//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDTLaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int MaBanner { get; set; }
        public string HinhAnh { get; set; }
        public string LienKet { get; set; }
        public string MoTa { get; set; }
    }
}
