//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDTLaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhapKho
    {
        public int MaChiTiet { get; set; }
        public Nullable<int> MaPhieuNhap { get; set; }
        public int MaSanPham { get; set; }
        public int SoLuong { get; set; }
        public decimal GiaNhap { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual PhieuNhapKho PhieuNhapKho { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
